ip = "http://192.168.10.196"

[[endpoints]]
path = "show/text/HiBaby"

[[endpoints]]
path = "show/text/HiYou"

[[endpoints]]
path = "pick/datetime.local.date"

[[endpoints]]
path = "show/text/Wow"


[[endpoints]]
path = "pick/cm.bitnodes.reachable_bitcoin_nodes"

[[endpoints]]
path = "pick/cm.markets.sats_per_dollar"

